
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmCalcAvanz extends javax.swing.JFrame {

    /**
     * Creates new form jfrmCalcAvanz
     */
    LocalDate fechaActual = LocalDate.now();
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE, MMM, YYYY");
    String fechaformat = fechaActual.format(formato);
    //Variables públicas
    double valor1, valor2;
    double resp;
    public jfrmCalcAvanz() {
        initComponents();
        this.setTitle("Calculadora");
        this.setSize(500, 500);
        //Mostrar la fecha en caja de texto
        jtfFecha.setText(fechaformat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfNum1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbFecha = new javax.swing.JLabel();
        jtfFecha = new javax.swing.JTextField();
        jbtNum2 = new javax.swing.JButton();
        jbtNum1 = new javax.swing.JButton();
        jtfNum2 = new javax.swing.JTextField();
        jbtMultiplicacion = new javax.swing.JButton();
        jbtDivision = new javax.swing.JButton();
        jbtResta = new javax.swing.JButton();
        jlbResultado = new javax.swing.JLabel();
        jbtSuma = new javax.swing.JButton();
        jlbResultado1 = new javax.swing.JLabel();
        jbtSuma1 = new javax.swing.JButton();
        jbtResta1 = new javax.swing.JButton();
        jbtMultiplicacion1 = new javax.swing.JButton();
        jbtDivision1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlbFecha1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfFah = new javax.swing.JTextField();
        jtfCel = new javax.swing.JTextField();
        jbtNum5 = new javax.swing.JButton();
        jbtNum6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfFecha1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jtfNum1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jtfNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNum1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Ingrese otro Número:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Ingrese un Número:");

        jlbFecha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlbFecha.setText("Fecha:");

        jtfFecha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jtfFecha.setEnabled(false);

        jbtNum2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtNum2.setText("+ 1");
        jbtNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNum2ActionPerformed(evt);
            }
        });

        jbtNum1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtNum1.setText("+ 1");
        jbtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNum1ActionPerformed(evt);
            }
        });

        jtfNum2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jbtMultiplicacion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtMultiplicacion.setText("x");
        jbtMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMultiplicacionActionPerformed(evt);
            }
        });

        jbtDivision.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtDivision.setText("÷");
        jbtDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDivisionActionPerformed(evt);
            }
        });

        jbtResta.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtResta.setText("-");
        jbtResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRestaActionPerformed(evt);
            }
        });

        jlbResultado.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlbResultado.setText("Resultado:");

        jbtSuma.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtSuma.setText("+");
        jbtSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSumaActionPerformed(evt);
            }
        });

        jlbResultado1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlbResultado1.setText("Resultado:");

        jbtSuma1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtSuma1.setText("+");
        jbtSuma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSuma1ActionPerformed(evt);
            }
        });

        jbtResta1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtResta1.setText("-");
        jbtResta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResta1ActionPerformed(evt);
            }
        });

        jbtMultiplicacion1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtMultiplicacion1.setText("x");
        jbtMultiplicacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMultiplicacion1ActionPerformed(evt);
            }
        });

        jbtDivision1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtDivision1.setText("÷");
        jbtDivision1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDivision1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(23, 195, 90));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jlbFecha1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlbFecha1.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Grados Fahrenheit");

        jtfFah.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jtfFah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfFah.setText("32.00");
        jtfFah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFahActionPerformed(evt);
            }
        });

        jtfCel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jtfCel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfCel.setText("0.00");
        jtfCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCelActionPerformed(evt);
            }
        });

        jbtNum5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtNum5.setText("+ 1");
        jbtNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNum5ActionPerformed(evt);
            }
        });

        jbtNum6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtNum6.setText("+ 1");
        jbtNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNum6ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("Grados Celsius");

        jtfFecha1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jtfFecha1.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfCel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jtfFah, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtNum5)
                            .addComponent(jbtNum6))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlbFecha1)
                        .addGap(18, 18, 18)
                        .addComponent(jtfFecha1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbFecha1)
                    .addComponent(jtfFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtNum5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfFah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtNum6))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMultiplicacionActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1 * valor2;
        jlbResultado.setText("La multiplicación es: "+resp);
    }//GEN-LAST:event_jbtMultiplicacionActionPerformed

    private void jbtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNum1ActionPerformed
        //Capturar el valor de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor1 = valor1 + 1;//Suma el valor de la caja de texto una unidad.
        jtfNum1.setText(String.valueOf(valor1));
        resp = resp +1;
    }//GEN-LAST:event_jbtNum1ActionPerformed

    private void jbtNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNum2ActionPerformed
        //Capturar el valor de la caja de texto.
        valor2 = Integer.parseInt(jtfNum2.getText());
        valor2 = valor2 + 1;//Suma el valor de la caja de texto una unidad.
        jtfNum2.setText(String.valueOf(valor2));
        resp = resp +1;
    }//GEN-LAST:event_jbtNum2ActionPerformed

    private void jtfNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNum1ActionPerformed

    private void jbtSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSumaActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1 + valor2;
        jlbResultado.setText(""+resp);
    }//GEN-LAST:event_jbtSumaActionPerformed

    private void jbtRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRestaActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1-valor2;
        jlbResultado.setText(""+resp);
    }//GEN-LAST:event_jbtRestaActionPerformed

    private void jbtDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDivisionActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1/valor2;
        jlbResultado.setText(""+resp);
    }//GEN-LAST:event_jbtDivisionActionPerformed

    private void jtfCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCelActionPerformed

    private void jbtSuma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSuma1ActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1 + valor2;
        jlbResultado.setText("La suma es"+resp);
    }//GEN-LAST:event_jbtSuma1ActionPerformed

    private void jbtResta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResta1ActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1-valor2;
        jlbResultado.setText("La resta es: "+resp);
    }//GEN-LAST:event_jbtResta1ActionPerformed

    private void jbtDivision1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDivision1ActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1/valor2;
        jlbResultado.setText("La división es: "+resp);
    }//GEN-LAST:event_jbtDivision1ActionPerformed

    private void jbtMultiplicacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMultiplicacion1ActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1 * valor2;
        jlbResultado.setText("La multiplicación es: "+resp);
    }//GEN-LAST:event_jbtMultiplicacion1ActionPerformed

    private void jbtNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNum5ActionPerformed
        //Capturar el valor de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor1 = valor1 + 1;//Suma el valor de la caja de texto una unidad.
        jtfNum1.setText(String.valueOf(valor1));
        resp = valor1 + 1;
        jtfFah.setText(""+valor1 * 1.8 + 32);
    }//GEN-LAST:event_jbtNum5ActionPerformed

    private void jbtNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNum6ActionPerformed
        //Capturar el valor de la caja de texto.
        valor2 = Integer.parseInt(jtfCel.getText());
        valor2 = valor2 + 1;
        jtfCel.setText(String.valueOf(valor2));
        valor1 = (valor1 * 1.8)+32;
        jtfFah.setText(String.valueOf(valor1));
    }//GEN-LAST:event_jbtNum6ActionPerformed

    private void jtfFahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcAvanz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcAvanz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcAvanz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcAvanz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalcAvanz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtDivision;
    private javax.swing.JButton jbtDivision1;
    private javax.swing.JButton jbtMultiplicacion;
    private javax.swing.JButton jbtMultiplicacion1;
    private javax.swing.JButton jbtNum1;
    private javax.swing.JButton jbtNum2;
    private javax.swing.JButton jbtNum5;
    private javax.swing.JButton jbtNum6;
    private javax.swing.JButton jbtResta;
    private javax.swing.JButton jbtResta1;
    private javax.swing.JButton jbtSuma;
    private javax.swing.JButton jbtSuma1;
    private javax.swing.JLabel jlbFecha;
    private javax.swing.JLabel jlbFecha1;
    private javax.swing.JLabel jlbResultado;
    private javax.swing.JLabel jlbResultado1;
    private javax.swing.JTextField jtfCel;
    private javax.swing.JTextField jtfFah;
    private javax.swing.JTextField jtfFecha;
    private javax.swing.JTextField jtfFecha1;
    private javax.swing.JTextField jtfNum1;
    private javax.swing.JTextField jtfNum2;
    // End of variables declaration//GEN-END:variables
}
