
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmCalcbasic extends javax.swing.JFrame {

    /**
     * Creates new form jfrmCalcbasic
     */
    LocalDate fechaActual = LocalDate.now();
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE, MMM, YYYY");
    String fechaformat = fechaActual.format(formato);
    //Variables públicas
    int valor1, valor2;
    double resp;
    public jfrmCalcbasic() {
        initComponents();
        this.setTitle("Calculadora");
        this.setSize(500, 500);
        //Mostrar la fecha en caja de texto
        jtfFecha.setText(fechaformat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbFecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbResultado = new javax.swing.JLabel();
        jtfNum2 = new javax.swing.JTextField();
        jtfNum1 = new javax.swing.JTextField();
        jbtSuma = new javax.swing.JButton();
        jbtResta = new javax.swing.JButton();
        jbtDivision = new javax.swing.JButton();
        jbtMultiplicacion = new javax.swing.JButton();
        jbtNum1 = new javax.swing.JButton();
        jbtNum2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jlbFecha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlbFecha.setText("Fecha:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Ingrese otro Número:");

        jlbResultado.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlbResultado.setText("Resultado:");

        jtfNum2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jtfNum1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jtfNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNum1ActionPerformed(evt);
            }
        });

        jbtSuma.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtSuma.setText("+");
        jbtSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSumaActionPerformed(evt);
            }
        });

        jbtResta.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtResta.setText("-");
        jbtResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRestaActionPerformed(evt);
            }
        });

        jbtDivision.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtDivision.setText("÷");
        jbtDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDivisionActionPerformed(evt);
            }
        });

        jbtMultiplicacion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtMultiplicacion.setText("x");
        jbtMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMultiplicacionActionPerformed(evt);
            }
        });

        jbtNum1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtNum1.setText("+ 1");
        jbtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNum1ActionPerformed(evt);
            }
        });

        jbtNum2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jbtNum2.setText("+ 1");
        jbtNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNum2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Ingrese un Número:");

        jtfFecha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jtfFecha.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jbtSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jbtResta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jbtMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtNum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbFecha)
                        .addGap(18, 18, 18)
                        .addComponent(jtfFecha)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jlbResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbFecha)
                    .addComponent(jtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtNum1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtNum2))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSuma)
                    .addComponent(jbtMultiplicacion)
                    .addComponent(jbtResta)
                    .addComponent(jbtDivision))
                .addGap(18, 18, 18)
                .addComponent(jlbResultado)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRestaActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1-valor2;
        jlbResultado.setText("La resta es: "+resp);
    }//GEN-LAST:event_jbtRestaActionPerformed

    private void jbtDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDivisionActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1/valor2;
        jlbResultado.setText("La división es: "+resp);
    }//GEN-LAST:event_jbtDivisionActionPerformed

    private void jbtMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMultiplicacionActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1 * valor2;
        jlbResultado.setText("La multiplicación es: "+resp);
    }//GEN-LAST:event_jbtMultiplicacionActionPerformed

    private void jbtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNum1ActionPerformed
        //Capturar el valor de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor1 = valor1 + 1;//Suma el valor de la caja de texto una unidad.
        jtfNum1.setText(String.valueOf(valor1));
    }//GEN-LAST:event_jbtNum1ActionPerformed

    private void jbtNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNum2ActionPerformed
        //Capturar el valor de la caja de texto.
        valor2 = Integer.parseInt(jtfNum2.getText());
        valor2 = valor2 + 1;//Suma el valor de la caja de texto una unidad.
        jtfNum2.setText(String.valueOf(valor2));
    }//GEN-LAST:event_jbtNum2ActionPerformed

    private void jbtSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSumaActionPerformed
        //Solicitar los valores de la caja de texto.
        valor1 = Integer.parseInt(jtfNum1.getText());
        valor2 = Integer.parseInt(jtfNum2.getText());
        resp = valor1 + valor2;
        jlbResultado.setText("La suma es: "+resp);
    }//GEN-LAST:event_jbtSumaActionPerformed

    private void jtfNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNum1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcbasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcbasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcbasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcbasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalcbasic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtDivision;
    private javax.swing.JButton jbtMultiplicacion;
    private javax.swing.JButton jbtNum1;
    private javax.swing.JButton jbtNum2;
    private javax.swing.JButton jbtResta;
    private javax.swing.JButton jbtSuma;
    private javax.swing.JLabel jlbFecha;
    private javax.swing.JLabel jlbResultado;
    private javax.swing.JTextField jtfFecha;
    private javax.swing.JTextField jtfNum1;
    private javax.swing.JTextField jtfNum2;
    // End of variables declaration//GEN-END:variables
}
