/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmCalc extends javax.swing.JFrame {
    //Variables restringidas - Privada
    private String entrada = "";
    private int n1, n2;
    private String op;
    /**
     * Creates new form jfrmCalc
     */
    public jfrmCalc() {
        initComponents();
        this.setTitle("Calculadora");
        this.setSize(300, 350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfCantidad = new javax.swing.JTextField();
        jbt8 = new javax.swing.JButton();
        jbt9 = new javax.swing.JButton();
        jbt7 = new javax.swing.JButton();
        jbt4 = new javax.swing.JButton();
        jbt2 = new javax.swing.JButton();
        jbt1 = new javax.swing.JButton();
        jbt3 = new javax.swing.JButton();
        jbt5 = new javax.swing.JButton();
        jbt6 = new javax.swing.JButton();
        jbtSuma = new javax.swing.JButton();
        jbtResta = new javax.swing.JButton();
        jbtMulti = new javax.swing.JButton();
        jbt0 = new javax.swing.JButton();
        jbtDivision = new javax.swing.JButton();
        jbtIgual = new javax.swing.JButton();
        jbtBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtfCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtfCantidad.setText("0");
        jtfCantidad.setEnabled(false);

        jbt8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt8.setText("8");
        jbt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt8ActionPerformed(evt);
            }
        });

        jbt9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt9.setText("9");
        jbt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt9ActionPerformed(evt);
            }
        });

        jbt7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt7.setText("7");
        jbt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt7ActionPerformed(evt);
            }
        });

        jbt4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt4.setText("4");
        jbt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt4ActionPerformed(evt);
            }
        });

        jbt2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt2.setText("2");
        jbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt2ActionPerformed(evt);
            }
        });

        jbt1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt1.setText("1");
        jbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt1ActionPerformed(evt);
            }
        });

        jbt3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt3.setText("3");
        jbt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt3ActionPerformed(evt);
            }
        });

        jbt5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt5.setText("5");
        jbt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt5ActionPerformed(evt);
            }
        });

        jbt6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt6.setText("6");
        jbt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt6ActionPerformed(evt);
            }
        });

        jbtSuma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtSuma.setText("+");
        jbtSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSumaActionPerformed(evt);
            }
        });

        jbtResta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtResta.setText("-");
        jbtResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRestaActionPerformed(evt);
            }
        });

        jbtMulti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtMulti.setText("x");
        jbtMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMultiActionPerformed(evt);
            }
        });

        jbt0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt0.setText("0");
        jbt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt0ActionPerformed(evt);
            }
        });

        jbtDivision.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtDivision.setText("/");
        jbtDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDivisionActionPerformed(evt);
            }
        });

        jbtIgual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtIgual.setText("=");
        jbtIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIgualActionPerformed(evt);
            }
        });

        jbtBorrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtBorrar.setText("A/C");
        jbtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbt4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSuma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtMulti))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbt7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbt8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbt9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbt0)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtDivision))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbt1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbt2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbt3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtResta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtIgual))
                        .addComponent(jbtBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfCantidad)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt7)
                    .addComponent(jbt8)
                    .addComponent(jbt9)
                    .addComponent(jbtDivision)
                    .addComponent(jbt0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSuma)
                    .addComponent(jbt4)
                    .addComponent(jbt5)
                    .addComponent(jbt6)
                    .addComponent(jbtMulti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtResta)
                    .addComponent(jbtIgual)
                    .addComponent(jbt3)
                    .addComponent(jbt2)
                    .addComponent(jbt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtBorrar)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt7ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 7;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt7ActionPerformed

    private void jbt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt8ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 8;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt8ActionPerformed

    private void jbt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt9ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 9;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt9ActionPerformed

    private void jbt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt0ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 0;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt0ActionPerformed

    private void jbt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt4ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 4;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt4ActionPerformed

    private void jbt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt5ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 5;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt5ActionPerformed

    private void jbt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt6ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 6;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt6ActionPerformed

    private void jbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt1ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 1;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt1ActionPerformed

    private void jbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt2ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 2;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt2ActionPerformed

    private void jbt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt3ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 3;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt3ActionPerformed

    private void jbtSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSumaActionPerformed
        // TODO add your handling code here:
        n1 = Integer.parseInt(entrada);
        entrada = "";
        op = "+";
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbtSumaActionPerformed

    private void jbtRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRestaActionPerformed
        // TODO add your handling code here:
        n1 = Integer.parseInt(entrada);
        entrada = "";
        op = "-";
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbtRestaActionPerformed

    private void jbtMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMultiActionPerformed
        // TODO add your handling code here:
        n1 = Integer.parseInt(entrada);
        entrada = "";
        op = "x";
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbtMultiActionPerformed

    private void jbtDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDivisionActionPerformed
        // TODO add your handling code here:
        n1 = Integer.parseInt(entrada);
        entrada = "";
        op = "/";
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbtDivisionActionPerformed

    private void jbtIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIgualActionPerformed
        // TODO add your handling code here:
        double resultado;
        n2 = Integer.parseInt(entrada);
        jtfCantidad.setText("");
        if (op.equals("+")){
            resultado = n1 + n2;
            entrada = String.valueOf(resultado);
            jtfCantidad.setText(entrada);
        }
        else if (op.equals("-")){
            resultado = n1 - n2;
            entrada = String.valueOf(resultado);
            jtfCantidad.setText(entrada);
        }
        else if (op.equals("x")){
            resultado = n1 * n2;
            entrada = String.valueOf(resultado);
            jtfCantidad.setText(entrada);
        }
        else if (op.equals("/")){
            resultado = n1 / n2;
            entrada = String.valueOf(resultado);
            jtfCantidad.setText(entrada);
        }
    }//GEN-LAST:event_jbtIgualActionPerformed

    private void jbtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBorrarActionPerformed
        // TODO add your handling code here:
        entrada = "0";
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbtBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbt0;
    private javax.swing.JButton jbt1;
    private javax.swing.JButton jbt2;
    private javax.swing.JButton jbt3;
    private javax.swing.JButton jbt4;
    private javax.swing.JButton jbt5;
    private javax.swing.JButton jbt6;
    private javax.swing.JButton jbt7;
    private javax.swing.JButton jbt8;
    private javax.swing.JButton jbt9;
    private javax.swing.JButton jbtBorrar;
    private javax.swing.JButton jbtDivision;
    private javax.swing.JButton jbtIgual;
    private javax.swing.JButton jbtMulti;
    private javax.swing.JButton jbtResta;
    private javax.swing.JButton jbtSuma;
    private javax.swing.JTextField jtfCantidad;
    // End of variables declaration//GEN-END:variables
}
